[package]
name = "ms-nrbf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
thiserror = "1.0.40"
num_enum = "0.5.11"
chrono = "0.4.24"
indexmap = "1.9.3"